services:
  - type: web
    name: ai-detector-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_DEBUG
        value: "False"
      - key: MODEL_NAME
        value: "prasoonmhwr/ai_detection_model"
      - key: REDIS_URL
        value: "redis://redis:6379/0"